export default {
  getStart: 'Get Started',
  language: 'Language',
  Login: 'Login',
  login: 'login',
  emailPlaceholder: 'Email....',
  next: 'Next',
  noAccount: 'You dont have an account please',
  haveAccount: 'You already have an account please',
  Register: 'Register',
  register: 'register',
  alert: `Email can't be empty`,
  security: 'Security',
  passwordPlaceholder: 'Password....',
  rememberpass: 'Remember password',
  confirmpass: 'Confirm password...',
  logout: 'Logout',
  logoutAlert: 'Logout successful',
  loginSuccess: 'Login successful',
};
