export default {
  getStart: 'စတင်ရန်',
  language: 'ဘာသာစကား',
  login: 'အကောင့်ဝင်ပါ',
  Login: 'အကောင့်ဝင်ပါ',
  emailPlaceholder: 'အီးမေးလ်....',
  next: 'နောက်သို့',
  noAccount: 'သင့်မှာ အကောင့်မရှိပူးလား ကျေးဇူးပြု၍',
  haveAccount: 'သင့်မှာ အကောင့်ရှိသလား ကျေးဇူးပြု၍',
  register: 'အကောင့်အသစ်ဖွင့်ပါ',
  Register: 'အကောင့်အသစ်ဖွင့်ပါ',
  alert: `အီးမေးလ် ထည့်သွင်းပါ`,
  security: 'လုံခြုံရေး',
  rememberpass: 'လျှို့ဝှက်နံပတ် မှတ်ထားသည်',
  confirmpass: 'လျှို့ဝှက်နံပတ် ထပ်ရိုက်ပါ...',
  passwordPlaceholder: 'လျှို့ဝှက်နံပတ်....',
  logout: 'ထွက်မည်',
  logoutAlert: 'အကောင့် ထွက်ပြီးပါပြီး',
  loginSuccess: 'အကောင့်ဝင်ရောက်ခြင်း အောင်မြင်ပါသည်',
};
